language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - npm i -g serverless
deploy:
  - provider: script
    script: npm i && npm run deploy
    on:
      branch: master
